name: flutter_application_1
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  pinput: ^2.1.4
  qr_code_scanner: ^0.7.0
  shared_preferences: ^2.0.13
  otp: ^3.0.2
  base32: ^2.1.1
  path_provider: ^2.0.9
  flutter_swipe_action_cell: ^2.2.0
  custom_pop_up_menu: ^1.2.3+1
  gesture_password_widget: ^2.0.0
  encrypt: ^5.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
